# Generated by Django 3.0.8 on 2020-08-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200804_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='image_link',
            field=models.URLField(default='', max_length=400),
        ),
    ]
