# Generated by Django 3.0.8 on 2020-08-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200810_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='choice_type',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsstory',
            name='cuisine_type',
            field=models.CharField(choices=[('French', 'French'), ('Italian', 'Italian'), ('Modern Australian', 'Modern Australian')], default='Modern Australian', max_length=20),
        ),
    ]
