# Generated by Django 3.0.8 on 2020-08-11 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200811_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsstory',
            old_name='cuisine_type',
            new_name='category_type',
        ),
    ]
