# Generated by Django 3.0.8 on 2020-08-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200811_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='category_type',
        ),
        migrations.AddField(
            model_name='newsstory',
            name='gender',
            field=models.CharField(blank=True, choices=[('x', 'Male'), ('y', 'Female')], default='', max_length=60, verbose_name='gender'),
        ),
    ]
