# Generated by Django 3.0.8 on 2020-08-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200812_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='choice_type',
        ),
        migrations.RemoveField(
            model_name='newsstory',
            name='gender',
        ),
        migrations.AddField(
            model_name='newsstory',
            name='category',
            field=models.CharField(blank=True, choices=[('About', 'About'), ('Adventures', 'Adventures'), ('Friends', 'Friends'), ('Family', 'Family')], default='No category assigned', max_length=60, verbose_name='gender'),
        ),
    ]
