# Generated by Django 3.0.8 on 2020-08-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20200814_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsstory',
            name='category',
            field=models.CharField(blank=True, choices=[('About', 'About'), ('Adventures', 'Adventures'), ('Friends', 'Friends'), ('Family', 'Family')], default='No Category Assigned', max_length=60, verbose_name='category'),
        ),
    ]
